/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductCreateRouteImport } from './routes/product/create'
import { Route as ProductEditIdRouteImport } from './routes/product/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCreateRoute = ProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductEditIdRoute = ProductEditIdRouteImport.update({
  id: '/product/edit/$id',
  path: '/product/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/create': typeof ProductCreateRoute
  '/product/edit/$id': typeof ProductEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/create': typeof ProductCreateRoute
  '/product/edit/$id': typeof ProductEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/create': typeof ProductCreateRoute
  '/product/edit/$id': typeof ProductEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product/create' | '/product/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product/create' | '/product/edit/$id'
  id: '__root__' | '/' | '/product/create' | '/product/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductCreateRoute: typeof ProductCreateRoute
  ProductEditIdRoute: typeof ProductEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/create': {
      id: '/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof ProductCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/edit/$id': {
      id: '/product/edit/$id'
      path: '/product/edit/$id'
      fullPath: '/product/edit/$id'
      preLoaderRoute: typeof ProductEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductCreateRoute: ProductCreateRoute,
  ProductEditIdRoute: ProductEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
